---
title: "Part 4: Doing more with data science"
subtitle: "Southern Wesleyan University, EdD Residency"
author: "Joshua M. Rosenberg, Ph.D, Assistant Professor, University of Tennessee, Knoxville"
date: "June 30, 2020"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, custom.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)

library(knitr)
library(tidyverse)
library(xaringan)
library(dataedu)

joro_years <- round(as.numeric(difftime(as.Date(Sys.Date()), Sys.getenv("joro_bday"), unit="weeks"))/52.25, 1)
```

class: inverse, center, middle

# Welcome back!

---

class: inverse, center, middle

# *Big idea*: Data science methods can assist and enhance your work with data.

---

# Homebase

*These will appear in every presentation throughout the day today*

**All materials here:**
https://github.com/jrosen48/swu-data-sci

**RStudio Cloud**
https://rstudio.cloud/project/1427304

**Ask questions on Google Docs:**
https://docs.google.com/document/d/1zB3IilyuU0khd10DWQNn44peOkVNI-OLyxRW6WFW5Qw/edit

**Ask questions in Zoom chat!**

---

# Agenda

### Part 1: Getting up and running
### Part 2: Visualizing and exploring data
### Part 3: Modeling and understanding data
### *Part 4: Doing more with data science*

---

# Text analysis

- Text analysis is an example of a data science technique that *may* be useful to you
- A bit on the epistemology of work with data:
   - We're accustomed to thinking of data as that which is stored in rows and columns in spreadsheets
   - But, not all data takes this form
- What data we collect, how we decide to collect it, and how we analyze it are decisions that we make
- Think about the kinds of data you want to collect---and why---to answer the questions *you* want to answer

---

# Text analysis 

*Let's hop over to the demo doc for part 4!* (optional)

---

class: inverse, center, middle

# Helpful resources and finding help

---

# Resources

- http://r4ds.had.co.nz/
- https://datascienceineducation.com
  - https://www.routledge.com/Data-Science-in-Education-Using-R/Estrellado-Freer-Mostipak-Rosenberg-Velasquez/p/book/9780367422257
- https://learningstatisticswithr.com/
- https://education.rstudio.com/learn/beginner/
- More here: https://datascienceineducation.com/c18.html

---

# Getting help

- Try to find out what the specific problem is
  -  Identify what is *not* causing the problem
- Highly-recommended: RStudio Community - https://community.rstudio.com/
- Reach out to each other---sharing what is causing an issue can often help to clarify the problem
- "Unplug and plug it back in" - restart R, close and reopen R
- Seek out workshops and other learning opportunities
- Consider using RStudio Cloud 
- Reach out to your faculty; it is so great that you're learning R
- Reach out to me!
- General strategies on learning more: https://datascienceineducation.com/c17.html

---

class: inverse, center, middle

# Conclusion

---

# *Discuss in groups!*

- What challenges did you face?
- What successes did you face?
- What questions do you still have?

---

class: inverse, center, middle

# *Big idea*: Data science methods can assist and enhance your work with data.

---

class: inverse, center, middle

# Thank you and contact!

@jrosenberg6432
jmrosenberg@utk.edu
https://joshuamrosenberg.com

---

# Post-survey (by email)

~ 5-minutes or less

https://utk.co1.qualtrics.com/jfe/form/SV_8iWTkEepqIeBEW1